#!/usr/bin/env bash
# script to display "To infinity and beyond" infinitely with sleep 2. Print "I am invincible!!!" when recieved SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
i=0
while [ $i ]; do
      echo 'To infinity and beyond'
      sleep 2
done
