#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd only displaying username, user id, home directory path for user
input="/etc/passwd"
while IFS= read -r line; do
      echo "$line" | cut -f1,3,6 -d':'
done < $input